swagger: 2.0
info:
  description: This specification documents the public API of easy:ems. Note that details about authentication/authorization are documented in a separate authentication document.
  version: 1.0
  title: Easy:ems Public API
schemes:
- http
consumes:
- application/json
produces:
- application/json
basePath: /v1

tags:
- name: placeholder


paths:

  /student/courses:
    get:
      responses:
        200:
          description: Courses to which the student has access.
          schema:
            type: array
            items:
              $ref: '#/definitions/StudentCourse'

  /student/courses/{courseId}/exercises:
    get:
      parameters:
      - $ref: '#/parameters/CourseId'
      responses:
        200:
          description: Exercises to which the student has access.
          schema:
            type: array
            items:
              $ref: '#/definitions/StudentExercise'

  /student/courses/{courseId}/exercises/{courseExerciseId}:
    get:
      parameters:
      - $ref: '#/parameters/CourseId'
      - $ref: '#/parameters/CourseExerciseId'
      responses:
        200:
          description: Exercise details.
          schema:
            $ref: '#/definitions/StudentExerciseDetails'

  /student/courses/{courseId}/exercises/{courseExerciseId}/submissions/latest:
    get:
      parameters:
      - $ref: '#/parameters/CourseId'
      - $ref: '#/parameters/CourseExerciseId'
      responses:
        200:
          description: Latest submission to this exercise.
          schema:
            $ref: '#/definitions/Submission'

  /student/courses/{courseId}/exercises/{courseExerciseId}/submissions:
    get:
      parameters:
      - $ref: '#/parameters/CourseId'
      - $ref: '#/parameters/CourseExerciseId'
      responses:
        200:
          description: All submissions to this exercise.
          schema:
            type: array
            items:
              $ref: '#/definitions/Submission'

    post:
      parameters:
      - $ref: '#/parameters/CourseId'
      - $ref: '#/parameters/CourseExerciseId'
      - name: submission
        in: body
        schema:
          properties:
              TODO
      responses:
        201:
          description: TODO
          headers:
            Location:
              description: TODO



parameters:

  CourseId:
    name: courseId
    in: path
    required: true
    type: string

  CourseExerciseId:
    name: courseExerciseId
    in: path
    required: true
    type: string

  SubmissionId:
    name: submissionId
    in: path
    required: true
    type: string


definitions:

  StudentCourse:
    properties:
      id:
        type: string
      title:
        type: string
      next_deadline:
        type: string
        format: date-time
      progress:
        description: TODO
        type: integer

  StudentExercise:
    properties:
      id:
        type: string
      title:
        type: string
      deadline:
        type: string
        format: date-time
      status:
        $ref: '#/definitions/ExerciseStatus'
      grade:
        description: TODO
        type: integer

  StudentExerciseDetails:
    properties:
      title:
        type: string
      text_html:
        type: string
      deadline:
        type: string
        format: date-time
      grader_type:
        $ref: '#/definitions/GraderType'
      threshold:
        type: integer

  Submission:
    properties:
      serial:
        type: integer
      solution:
        type: string
      grade:
        type: integer
      feedback:
        type: string
      time:
        type: string
        format: date-time



  # Enums
  ExerciseStatus:
    type: string
    description: TODO
    enum:
      - UNSTARTED
      - STARTED
      - COMPLETED

  GraderType:
    type: string
    description: TODO
    enum:
      - AUTO
      - TEACHER
